### ISSUE TITLE
Fixity Section

### ISSUE THREAD

**Issue by acoburn** [fcrepo/fcrepo-specification#100]

**Comment by barmintor** [comment]
We once had things organized in a similar fashion to what you describe, and the group (edit: two) of us writing fixity and versioning spec proposals at the time found it confusing to have to read all through the spec to see, eg, what a conforming server needs to do for GET on LDP-NR (this was also confusing to me trying to write test suites in Cavendish).

Without checking, I suspect that the text from section 1 is pretty old- maybe section 5 should be an appendix, since it really describes patterns of use and not requirements of behavior.

**Comment by acoburn** [comment]
@barmintor however you'd like to organize it is fine; I think there are decent arguments either way and at that point it's just a matter of style.

Section 1 isn't particularly old, but it does predate the removal of the normative sections in section 5. Having section 5 become more of an appendix or just a section with examples of use seems like a good idea.

**Comment by zimeon** [comment]
Discussed in API Call: Consider this closed with merge of #128, but note relation to #133 which is in-process
