### ISSUE TITLE
Clarify WebAC section

### ISSUE THREAD

**Issue by acoburn** [fcrepo/fcrepo-specification#101]
The WebAC section includes this statement

> Implementations must support extended control relationships in which the access control resource for some resource has its own access control resource and so on.

What does that mean? The phrase "extended control" does not appear in the Solid WebAC specification nor in the W3C wiki page for WebAC. And how does that differ from what is already defined as the `acl:Control` mode that is [already clearly defined](https://github.com/solid/web-access-control-spec#referring-to-the-acl-resource-itself) in the Solid WebAC specification?

The WebAC section also has this statement:

> Implementations must make access control resources discoverable via the Link: rel="acl" HTTP header, as discussed [here](https://github.com/solid/web-access-control-spec#acl-resource-location-discovery).

Referring to remote resources using a "here link" is generally bad practice. And if the Fedora specification is simply recapitulating what the Solid WebAC specification already states, why is this statement in the Fedora specification?

This also applies to this statement:

> 6.1 Inheritance §
> An implementation must respect [LDP]-containment for access control, as described [here](https://github.com/solid/web-access-control-spec#acl-inheritance-algorithm).

Why is the Fedora specification recapitulating statements from other specifications that it already requires?

**Comment by ajs6f** [comment]
All of that stuff dates to before the recognition that the Solid work is well ahead of the much older and no longer maintained W3C pages. That's why it reads so strangely. I'd be happy to see a PR straightening it all out.

**Comment by barmintor** [comment]
Since Solid is a normative reference for the spec, this all seems like it could be compactly stated as:
1. To configure access control restrictions, implementations `MUST` follow the recommendations of [SOLIDWEBAC].
2. the ACLR `MUST` be a LDP-RS
2. `<ldp:contains> MUST` be regarded as the axis of inheritance
3. the ACLR `SHOULD` be located in the implementing repository

Solid is designed to work with LDP but doesn't seem to take specific recourse to it, so our expectations in that vein need to be explicit. On the other hand, we should also be able to take Solid as read (as observed in this issue).

**Comment by ajs6f** [comment]
@barmintor Agreed, with one nitpick-- if we actually use Solid acronyms, we should define them locally in some way (maybe a link, maybe a quote).

**Comment by barmintor** [comment]
Sorry, by "this all" above I mean "a clarified section 6". It made sense in my head. @awoods I'm inclined to mark this "ready needs PR" if there's another :+1:.
