### ISSUE TITLE
Clarification of Preference-Applied header

### ISSUE THREAD

**Issue by acoburn** [fcrepo/fcrepo-specification#110]

**Comment by escowles** [comment]
I think this example is _exactly_ the situation this is meant to address — see #81.  In short, if a client sends a Prefer header with `include="http://www.w3.org/ns/ldp#PreferContainment"` and receives a response with no containment triples, the presence of the `Preference-Applied` header helps the client tell the difference between those triples not existing, as opposed to simply not being included in the response for whatever reason.

I don't think adding "successfully" helps here (because the question then becomes what does successfully mean).  But it may be helpful to add to that section something like "even if no additional triples were added to the response".

**Comment by acoburn** [comment]
OK, fair enough.
