### ISSUE TITLE
Clarification of InboundReferences

### ISSUE THREAD

**Issue by acoburn** [fcrepo/fcrepo-specification#119]

**Comment by escowles** [comment]
Including a triple with a blank node subject without any other context seems problematic.  So including the chain from a non-blank subject seems like a good approach:

```
<http://example.com/resource/1> ex:prop [
    dc:subject <http://example.com/resource/2> ] .
```

`/resource/3` and `/resource/4` seem more straightforward to me, since those triples can be included as-is.   But there is the issue that, without the single-subject rule, it seems hard to know what resource contains those triples.  Named-graphs seem like they could be a good fit there:

```
<http://example.com/resource/1> {
    <http://example.com/resource/in-domain-subject>
          dc:subject <http://example.com/resource/4> .
}
```

**Comment by acoburn** [comment]
Named graphs would be an excellent choice if the concrete RDF syntax supports datasets (TriG, NQuads, JSON-LD) but not otherwise (Turtle, NTriples, RDF/XML).
