### ISSUE TITLE
Clarification of resource version creation

### ISSUE THREAD

**Issue by acoburn** [fcrepo/fcrepo-specification#130]

**Comment by barmintor** [comment]
This is definitely an outstanding issue. Assuming the definition of the header, I don't think it requires client deferral here (the presence of the TimeMap is the advertisement after creation). There's a question about how to communicate the optionality of versioning on creation, where it s optional, though. I'm assuming that servers that supported removal of versioning for a resource would just let you HTTP DELETE the LDP-Cv, but maybe that too needs language.

**Comment by zimeon** [comment]
Going back to @acoburn's original point (will create another issues to @barmintor's point), I agree that lack of specification for what this link header is, is the biggest current hole in the versioning spec! We are in uncharted territory here because Memento is silent on such things, and F4 uses [URI patterns related the resource being versioned](https://wiki.duraspace.org/display/FEDORA4x/Versioning). I'll therefore kick off with a proposal to think about:

```
Link: <http://fedora.info/definitions/fcrepo#versioned>; rel="type"
```

It seems to me that the semantics are Fedora's own so it it thus reasonable to put it in our own namespace.

Per other LDP constraints, I think a server that does not support client managed versioning would respond with 4xx (likely 400) and a `...#constrainedBy` link to explanation of constraints.

**Comment by acoburn** [comment]
If a server does not support client-managed versioning but does support automatic server-managed versioning, then the resource would be versioned regardless of the presence of this header. And so in that case the header will, effectively, be ignored though the result will be the same.

In addition, RDF types are typically capitalized. For instance: `fcrepo:Version`. I would also tend to advocate for `Version` over `Versioned`, as it is my understanding that the HTTP request involves creating a "version" of a particular resource ("VersionedResource" is another possibility). That is: "version" is a noun and "versioned" is an adjective, and RDF Types are typically nouns, therefore, "version" would be a better fit.

**Comment by barmintor** [comment]
@acoburn "Version" would make me think of the Memento resource, but I think @zimeon is talking about the interaction model for the resource that has a timeMap. Is that right?

**Comment by zimeon** [comment]
I take the point about class being a noun, I think `fcrepo:VersionedResource` seems right.
