### ISSUE TITLE
Move discussion of `Depth` header for `DELETE` to atomic operation specification

### ISSUE THREAD

**Issue by ajs6f** [fcrepo/fcrepo-specification#136]
The action of a recursive `DELETE` is inherently concerned with more than one resource, and as such represents a case of atomic action in a RESTful API. For many good reasons, such operations were excluded from the "core" API document and moved to a separate document. This operation (`DELETE`-with-`Depth`) should also be moved to that document, for the same reasons.

**Comment by acoburn** [comment]
👍  thank you

**Comment by dannylamb** [comment]
I think it would be good to put a non-normative note above our deletion section stating that no guarantees of atomicity can be made on deletes affecting multiple resources.  Just because an operation affects multiple resources doesn't mean it's required to be atomic.

I do think an implementation that chooses to provide batch atomic operations should provide a way of doing this atomically, though.  So it certainly deserves space in the side-car spec.
