### ISSUE TITLE
Cross-domain Authorization?

### ISSUE THREAD

**Issue by awoods** [fcrepo/fcrepo-specification#168]
The [Solid spec](https://github.com/solid/web-access-control-spec#group-listings---implementation-notes) offers the possibility of referencing groups defined in other domains.

Do we want to support ACLs or groups that are out-of-domain?

**Comment by acoburn** [comment]
I would say this is an implementation decision. There are legitimate concerns about MITM attacks that could target such cross-domain auth scenarios. I certainly wouldn't implement this without thinking very hard about the use case. There are ways to make this work, but they are not simple.

**Comment by barmintor** [comment]
I'm 👍  @acoburn here- this is a huge requirement to require in any way, but I also wouldn't feel comfortable saying it mustn't be done if somebody has it sorted out.

**Comment by dannylamb** [comment]
I'm fine with leaving this up to implementors as well.

**Comment by zimeon** [comment]
Two cases:
  * This is a non-issue for [singular agents](https://github.com/solid/web-access-control-spec#singular-agent), the implementation does not need to dereference the agent-URI in `<> <acl:agent> <agent-URI>`
  * For [groups of agents](https://github.com/solid/web-access-control-spec#groups-of-agents) it is necessary for the implementation to dereference the group-listing-URI in `<> <acl:agentGroup> <group-listing-URI>` and I agree that cross-domain support should be an implementation decision.

How might the second case be handled? It seems that it would be fine for an implementation to reject a request to create an ACL with a cross-domain group agent-URI (fits under [LDPRS rules](https://fcrepo.github.io/fcrepo-specification/#httpPUTLDPRS) with 409 and link to `constrainedBy`). If an implementation instead allows the creation of ACL's with cross-domain group agent-URIs then it could either deny because it refuses to use the ACL (403?) or accept/deny based on other authorizations while ignoring the cross-domain one(s). All of these seem OK to me.

I we should probably explicitly permit local-only implementation:

> Implementations MAY restrict support for \[SOLIDWEBAC]  [groups of agents](https://github.com/solid/web-access-control-spec#groups-of-agents) to local Group Listing documents.

and perhaps comment on the security issue:

> Non-normative note: Implementation of support for \[SOLIDWEBAC] [groups of agents](https://github.com/solid/web-access-control-spec#groups-of-agents) requires retrieval of one or more Group Listing documents. Security implications should be considered if non-local Group Listing documents are supported.

**Comment by awoods** [comment]
Thanks, @zimeon .
It is worth noting that there is a parallel set of specification language that should probably be created relating to support of out-of-domain ACLs... in addition to out-of-domain groups.
