### ISSUE TITLE
ACL creation and linking -- be explicitly silent or specify?

### ISSUE THREAD

**Issue by zimeon** [fcrepo/fcrepo-specification#176]
The SOLIDWEBAC specification and the Fedora specification are both currently silent on how or when and ACL may be created and linked to the resource(s) it is designed to control access for. The following cases all seem conforming at present:

  * An implementation aiming to provide easy migration from [Fedora4 WebAC](https://wiki.duraspace.org/x/AJUpB) might require an additional type to indicate an ACL (currently an ACL is a BasicContainer with a specific type, which has children for Authorizations -- this has to change to single resource) and use the `acl:accessControl` property on a resource to indicate its ACL (this predicate _is_ in the [WAC ontology](http://www.w3.org/ns/auth/acl#) but is not mentioned in the SOLIDWEWAC spec) 
  * An implementation has a default ACL that applies to all resources and it never creates nor allows creation or linking of any other ACL (assumes #163)
  * One default ACL as previous bullet that can be edited to be the sole source of fine grained authorization data for many resources (sounds like scaling nightmare!)
  * An implementation automagically creates a new ACL for every resource created (based on some implementation policy, which _might (but need not)_  be based on the idea of inheritance at creation) and thus avoids the need for any inheritance when later determining which ACL applies 
  * An implementation allows creation of ACL documents by creation of an LDPRS that _smells like an ACL_ (I say this because ACLs are not typed), and is linked to a resource based on interpretation of the `acl:accessTo` (has rules determining whether linking happens for one or more resources, what to do if one of these already has an ACL, etc.)
  * An implementation allows linking an LDPRS to a resource as its ACL by some other means outside of Fedora and LDP specs
  * ... more I'm sure ...

IMO, we should _either_ be explicitly silent:

> Non-normative note: Behaviors regarding the creation of ACLs and associating them with the resources they control access for are not defined by \[SOLIDWEBAC] or this specification.

_or_ specify some restrictions.

(I believe that, given the understanding that an ACL is an LDPRS, and the `acl:Control` permission (#170), changes to an ACL can be made with PUT/PATCH as normal under LDP.)

**Comment by escowles** [comment]
I think it would be nice to at least specify one or more options for creating ACLs that should be supported.  Otherwise, any client wishing to create resources with ACLs will have to have special knowledge of the implementation's choices in that regard.

**Comment by birkland** [comment]
I like how the LDP spec deals with descriptions for LDP-NRs via `describedby`, and an analogous treatment for `acl` could be easy to understand without being overly burdensome;  i.e a server MAY create an ACL for any resource; if it does create an ACL, then it MUST expose it via a `Link <...>; rel=acl`.  Clients can then discover it, modify it, etc.    

I think several (most?) implementations of web acl do that.

**Comment by awoods** [comment]
I would suggest it is a requirement that one ACL could be applied to many resources distributed throughout the repository, to address both the scaling concern as well as to reduce duplication of policies.

Is there concern about specifying the current approach?

> An implementation aiming to provide easy migration from Fedora4 WebAC might require an additional type to indicate an ACL (currently an ACL is a BasicContainer with a specific type, which has children for Authorizations -- this has to change to single resource) and use the acl:accessControl property on a resource to indicate its ACL (this predicate is in the WAC ontology but is not mentioned in the SOLIDWEWAC spec)

**Comment by acoburn** [comment]
@awoods I have no concerns about making the "current approach" (i.e. the Fedora4 approach) a non-normative "implementation pattern". But under no circumstances, should that be the only option.

In terms of "address[ing] ... the scaling concern", yes, I can see how, in a single node implementation, it could be desirable to reduce to overall number of policies. However, there are other possibilities for implementations, and in a multi-partition scenario, you would absolutely want to ensure data locality (rather than reducing data redundancy), in which case, minimizing the number of ACLs would be counterproductive.

That is, the implementation that I am working towards is much more closely aligned with what is described in the SOLID WebAC spec than the current Fedora4 implementation.

There is also a real problem with the Fedora4 implementation w/r/t `acl:Control` and the use of `ldp:contains` for including Authorization statements in that ACL. (This is why support for `acl:Control` was never implemented). In short, you can only implement `acl:Control` if there is some very clear way to distinguish between Authorization statements and other user-supplied statements. And if user-triples are used in making that distinction (that is, if a regular LDP-RS can, at any time, become an ACL) there are some real challenges that enter into the implementation.

What I am trying to say is that the Fedora4 implementation of WebAC is problematic in a number of ways (some of which relate to limitations of the underlying Modeshape engine), and I really hope that _all_ implementations aren't required to follow that implementation pattern.

**Comment by acoburn** [comment]
@zimeon's original question posed here is very important. The SOLID WebAC is clear about linking to an "effective" or "existing" ACL, but it is silent on the following scenario:

Given a resource at `/root` and some ACL attached to `/root` (e.g. `/root.acl`, linked via a `Link: </root.acl> rel="acl"` header), and given also a resource `/root/a/b/c/resource` without an ACL (and no other, intermediate ACLs). Clearly, access to `/root/a/b/c/resource` would be governed by `/root.acl`. But if a client wants to create a specialized ACL for `/root/a/b/c/resource`, where does that ACL go? What is its location? Is there a link header that points to a currently non-existent location where a new ACL should be placed? The Fedora4 approach is to use the `acl:accessControl` triple and allow any arbitrary resource in the repository to be used as an ACL (there are issues -- though not insurmountable -- with this approach). In this scenario, a client does not necessarily have enough information to know where a new ACL should go for the child resource.

In my work with WebAC and Trellis, the best implementation option for me will be to (internally) use named graphs for ACL statements, stored directly with each resource (e.g. data locality) and automatically create ACL resources (exactly like one of @zimeon's scenarios listed above and echoed by @birkland), which makes ACLs easy to discover (for clients) and to enforce (for the server).

**Comment by escowles** [comment]
As I've said before, I think it would be good to specify one way that clients can declare what ACL should be used for newly-created resources.  There was some discussion of this at the last editor's meeting, and it would look something like:

* A client creating a resource may include a Link rel="acl" header pointing to an existing LDP-RS to use as an ACL.
* The server must respond with a 4xx if it isn't able to use that LDP-RS (not sure if this should be 400 or 409 or something else).

**Comment by acoburn** [comment]
@escowles when you write "it would be good to specify one way that clients can declare what ACL should be used", do you mean that the Fedora specification would identify a single way that this would work to the exclusion of any other way of linking to an ACL? Or do you mean that the specification would include a non-normative "implementation patterns" section?

**Comment by escowles** [comment]
@acoburn I don't think we should exclude other implementation patterns, including having a server-managed ACL link like you're describing for Trellis, or the Modeshape impl's pattern of including a triple pointing to the ACL.

But all things being equal, I think it would be good to specify one pattern for clients to specify their ACLs, because otherwise implementations that support that will naturally vary.

**Comment by acoburn** [comment]
@escowles as long as the Fedora specification's stance on ACL creation is non-normative (e.g. an "implementation pattern" section), that will be fine.

**Comment by whikloj** [comment]
Can I just ask a question, I was responding to [this thread](https://groups.google.com/forum/#!topic/fedora-tech/BkPY96JDj3Y) and I realized that the Solid Spec does not use the acl:accessControl property either.

I'm having (pragmatic) concerns/thoughts. Does that mean you check all ACLs to find any all that have an acl:accessTo for the resource you are requesting?

**Comment by acoburn** [comment]
@whikloj if the server implementation allows ACLs to be _anywhere_ in the repository, that could be a real problem (e.g. as is currently the case with F4), and I'm not entirely sure how one would solve it in the absence of using `acl:accessControl`. On the other hand, if the server restricts the locations where an ACL can be located for a given resource, then the problem becomes considerably easier. Adding this server-level restriction also makes the implementation of `acl:Control` much easier and makes `acl:accessControl` triples unnecessary.

**Comment by whikloj** [comment]
@acoburn that' s interesting. So the server will place the ACL in an expected location for each resource. 

Would that not mean that the `acl:accessTo` becomes much more restricted in what it could refer to? Because if you have two trees (B & C)  from root (A), then while an ACL on a resource in tree B (which would be in an expected location for that resource) could refer to a resource in tree C.

However there is no way that the resource in tree C would know it was covered by that ACL. 

I guess you could parse the ACLs (on insert/update) to validate that they are only referring to the expected resources.

I'm not particularly tied to `acl:accessControl` but I'm just seeing that removing it and `acl:accessToClass` (both of which have issues) causes you to move to add more ACLs to your repo to cover your resources.

Unless (and this is a viable option) I've misread the spec and so missed the substance of the discussion.

**Comment by acoburn** [comment]
@whikloj first of all, my implementation is _very_ different from Fedora4, but as the spec currently stands, it will be a conforming implementation, and an LDP client should have no issues interacting with it. One of those differences relates to how WebAC is implemented, and in this case, I took a lot of the "lessons learned" from implementing this in Fedora4.

You are correct that in my case the `acl:accessTo` predicate is quite restricted in terms of what it can refer to. In fact, it can _only_ refer to the resource that points to the ACL in question. (There are a number of policy-driven RDF constraints on the graphs that can be added/updated in Trellis, and this is another type of constraint -- advertised via an `ldp:constrainedBy` link header)

In terms of "adding more ACLs to your repo", that is true in a sense (given the implementation I'm working on), but it also makes perfect sense for the kinds of performance and scaling goals I have. And depending on how one looks at the underlying implementation, one could argue that there are actually _fewer_ resources in Trellis.

I would note that there is nothing in the spec that prohibits the use of `acl:accessControl` and `acl:accessTo` in order to refer to an ACL resource that exists in a different hierarchy, it's just that I'm following a different pattern -- a pattern which seems to be much more similar to what the SOLIDWEB folks are doing.

**Comment by whikloj** [comment]
@acoburn ok, I realize that the concerns I have are more of a server-side or implementation concern. The clients should be blissfully unaware, but I was just wondering what the general thoughts around this were. thanks.
