### ISSUE TITLE
How can a client tell if a server implements server-managed versioning?

### ISSUE THREAD

**Issue by zimeon** [fcrepo/fcrepo-specification#187]
Related to #186. Does a client create a resource and see if it is versioned, use some out-of-band means, or have explicit capability discovery?

**Comment by acoburn** [comment]
This one is easy:

1. Create a resource
2. Perform a HEAD request on that resource
3. See if memento headers are present.

**Comment by dannylamb** [comment]
Should we add a non-normative note describing this?

**Comment by zimeon** [comment]
What memento headers would indicate that the server implements server managed versioning? As far as I can see, at the end of @acoburn's [recipe](https://github.com/fcrepo/fcrepo-specification/issues/187#issuecomment-319147064) there will be a resource with one version, the headers would be the same whether server- or client-managed versioning is supported. (Additionally, I think that having to actually make a change in the repository is a bad way to do capability discovery.)

**Comment by zimeon** [comment]
(I note discussion of `OPTIONS` as might apply to this case too in #186)

**Comment by escowles** [comment]
@zimeon I think the way to solve that issue is #188:

The client can perform an OPTIONS request on the TimeMap to determine if the server supports client-managed versioning.  If it doesn't, the client can assume that the server does server-managed versioning.

**Comment by acoburn** [comment]
@zimeon one way to do this (without creating a new resource) is to make a request to a "regular" LDP resource and you'll see this header:

    Vary: Accept-DateTime

That means that the resource supports Memento datetime negotiation. If that header is present, then Memento-style versioning is supported.

Once you get to the memento resource (using `Accept-DateTime` in a subsequent request), that resource might contain these headers (I say "might" because this is just one way to do it -- Memento provides several patterns):

    Memento-DateTime: Wed, 09 Aug 2017 13:16:45 GMT
    Link: <url-for-original-resource>; rel="original"
    Link: <url-for-timegate-resource>; rel="timegate"
    Link: <url-for-timemap-resource>; rel="timemap"; from="..."; until="..."; type="application/link-format"

Then, with either a HEAD or OPTIONS request on the timemap, you should see the `Allow` header, which either allows mutable methods or it doesn't. That should be enough for a client to know if resources are server- or client-managed.

If a client is willing to create a resource, it can simply POST to a container and then perform a HEAD request on the new resource. If it contains the `Vary: Accept-DateTime` header, then server-managed versioning is in effect.
