### ISSUE TITLE
Capitalize MAY, MUST, SHOULD, etc in the rendered document

### ISSUE THREAD

**Issue by birkland** [fcrepo/fcrepo-specification#195]
Doing so helps the reader understand that such statements are normative, and emphasizes the level of requirement.

**Comment by awoods** [comment]
Thanks @birkland . If you have time, a PR would be great.

**Comment by zimeon** [comment]
??? -- The auth section (https://fcrepo.github.io/fcrepo-specification/#resource-authorization) seems to have MAY, MUST etc. emphasized in the same way as the rest of the spec. This is currently done with a color change rather than capitalization by the [ReSpec](https://github.com/w3c/respec/wiki/User's-Guide#rfc-2119) script, where all-caps is used in the source (are there some missing?). Is the question really about whether in all sections we should RDC2119 words capitalized? I don't see easy setting in ReSpec to do this but I see that the [LDP spec](https://www.w3.org/TR/ldp/) uses this style via the following inline CSS:

```
em.rfc2119 {
 text-transform:     lowercase;
 font-variant:       small-caps;
 font-style:         normal;
 color:              #900;
}
```

whereas the equivalent CSS our version/config of ReSpec is inserting is:

```
em.rfc2119 {
 text-transform: lowercase;
 font-style: normal;
 color: #900;
}
```

To me there is a slight trade-off between readability (current form better) vs. emphasis (caps form better).

**Comment by birkland** [comment]
Ah, I see.  The problem is that I'm partially colour blind, and cannot tell the difference between red text and black text unless I greatly magnify it.  So when I glanced at the rendered text, it looked like an omission to me; sorry.   Looking back at the LDP spec and magnifying it, it appears you're right - the MAY, MUST, etc is *also* red in that document!  I learn something new every day. 

In any case, changing the css to small-caps would be helpful to people with colour or vision problems, if you're open to it.

**Comment by zimeon** [comment]
I think you just provided a very convincing argument that color alone is not a good emphasis! I'm :+1: on working out how to fix the ReSpec config/css to do small caps ala LDP.

**Comment by birkland** [comment]
It looks like adding the `font-variant` to the `respec-w3c-common.js` does the trick.  PR on the way
