### ISSUE TITLE
Accept-Post: */*; p=0.0 clarification

### ISSUE THREAD

**Issue by bseeger** [fcrepo/fcrepo-specification#228]
There is the 'Accept-Post' response header that looks like this: `Accept-Post: */*; p=0.0` defined in this section of the spec: https://github.com/fcrepo/fcrepo-specification/blob/master/index.html#L784. I believe it is meant to indicate to the client that on a POST request no body may be submitted. 

Where is what `p` means defined, spec-wise?   Was it made up for this?  If so, you might want to spell out more what `p` means and the ABNF for it. 

Or is it meant to be a `q`? In which case that is not really done per https://tools.ietf.org/html/draft-wilde-accept-post-03#section-3  (actually there are no accept-params for Accept-Post).

**Comment by barmintor** [comment]
That looks like a typo (regarding p vs q). We should definitely reconsider the mechanism we're talking about there, but the two options I can see are both unappealing in some sense:

1. Ignore the Accept-Post spec on params - necessary because in this case the param negates the value.

2. Use a blank HTTP header `Accept-Post:`, which is I think ambiguous as far as the BNF for HTTP headers goes.

You're reading the intent correctly, tho - do you have any ideas for alternatives?

**Comment by zimeon** [comment]
Given other changes in #239 to clarify that the presence or not of a `Memento-Datetime` header determines whether the body is used or the current LDPRv is used, we don't need any (wrong) mention of `Accept-Post`. Agreed to:
  1. Remove mention of `Accept-Post` in third para of [4.3.4](https://fcrepo.github.io/fcrepo-specification/#ldpcvpost)
  2. Add explicit comment in first para of [4.3.4](https://fcrepo.github.io/fcrepo-specification/#ldpcvpost) that any request body is ignored
