### ISSUE TITLE
Modeshape Impl: Interaction models effectively can't be changed

### ISSUE THREAD

**Issue by escowles** [fcrepo/fcrepo-specification#229]
Section [3.2.1](https://fcrepo.github.io/fcrepo-specification/#httpPATCH-ixn-models) says that PATCH must not allow changing interaction models to non-subtypes.  But my reading of the [LDP ontology](https://www.w3.org/ns/ldp.rdf) and the types that the Modeshape implementation supports (NonRDFSource, BasicContainer, DirectContainer, IndirectContainer) means that you effectively can't change the interaction model after creating a resource (because none of those types are subtypes of any of the other types).

In order to allow changing to a subtype, an implementation would need to allow creating Resource, RDFSource or Container types.

I don't think this is a problem, but I wanted to raise it as a non-obvious consequence of the spec and the choices made in the Modeshape implementation.

**Comment by birkland** [comment]
Re-reading this, it has the consequence of:
* If a repository advertises a `Link rel=type` of a "most specific" type, then it cannot be changed (i.e If a resources advertises the header`Link: <ldp:BasicContainer"; rel=type`, that resource cannot be changed to DirectContainer, Container, etc).
* If a repository advertises a less-specific superclass in the link header (e.g. ldp:Container or ldp:Resource), then
  1. Absent _a priori_ knowledge, a client needs to infer its most specific interaction model by inspecting the triples by looking for `ldp:hasMemberRelation` or `ldp:isMemberOfRelation`  in order to know it is a direct container, or `ldp:insertedContentRelation` in order to know it is an indirect container.
  2. The most specific model can be changed (e.g BasicContainer to IndirectContainer) by modifying the resource's triples via `PUT` or `PATCH`

**Comment by awoods** [comment]
As a note, Cavendish creates `RDFSource`s in the absence of a client-provided interaction model.
