### ISSUE TITLE
What are the semantics of version restoration?

### ISSUE THREAD

**Issue by barmintor** [fcrepo/fcrepo-specification#238]
I'm still murky on what we mean by "version restoration" that isn't covered in other areas of the spec.

If restoring is a content or metadata overlay, then this is a simple update.

If it's something else (rolling back last modified dates, or deleting intervening versions, etc), I think that has to be explicated and proposed as a revision to the spec. I'd advocate dropping the language of revision otherwise.

**Comment by awoods** [comment]
My understanding of "version restoration" is a replacement of the current resource state with a previous version state. Since that can quite reasonably be achieved with a `GET /old-version` followed by `PUT /current`, I can see the argument for dropping notions of "version restoration" from the specification.

**Comment by escowles** [comment]
In many cases, the client could easily retrieve a previous version and update the resource.  But large binaries are one example of where it would be much more efficient to avoid the unnecessary round-trip.  So in that sense, this is really similar to the ingest-by-reference use case.

I would be 👍  on defining the ingest-by-reference mechanism in #236 for both POST and PUT, and using that instead of an explicit specification for version restoration.

**Comment by zimeon** [comment]
:+1: on the ingest-by-reference approach to adding an old-version as the current version. Whether this creates a new version will depend on server versioning behavior (manual/auto) and handling of any version deletes is a client issue.
