### ISSUE TITLE
Propose the addition of new terms to the LDP namespace

### ISSUE THREAD

**Issue by csarven** [fcrepo/fcrepo-specification#245]
In order to have wider exposure of the work here in particular to versioning which is in close proximity to LDP, can the LDP namespace be used for new terms like `fcrepo:VersionedResource`, and so it becomes `ldp:VersionedResource` ? Would that raise any issues for existing Fedora implementations? 

The addition of the new terms would require W3C approval of course, and I think the best place to push this through would be the W3C LDP-Next CG ( https://www.w3.org/community/ldpnext/ ). See also https://www.w3.org/2016/08/namespaces/#adding on the details.

**Comment by awoods** [comment]
Thanks for the suggestion, @csarven . 

At this point in the drafting of the Fedora API Specification, there should be no impact resulting from changing `fcrepo:VersionedResource` to `ldp:VersionedResource`.

However, it seems like it would make sense to introduce notions of versioning into the LDP-Next effort as a prerequisite to supposing appropriateness of adding the term to the LDP ontology. Thoughts?

**Comment by awoods** [comment]
Reflecting on this a bit more, we have started the conversation with the Memento folks regarding formalizing the types: 
* memento:TimeMap
* memento:Memento
* memento:TimeGate

In that context, it may make even more sense to bring `VersionedResource` into the (yet nonexistent) Memento ontology.

**Comment by escowles** [comment]
@awoods I like that idea.  And from that perspective, perhaps `memento:OriginalResource` is the appropriate term?

**Comment by zimeon** [comment]
To add words to my :+1: above on @escowles' https://github.com/fcrepo/fcrepo-specification/issues/245#issuecomment-338476766, I think that if we adopt a set of `memento` terms then using `memento:OriginalResource` instead of our own `VersionedResource` would make perfect sense. Using `ldp:VersionedResource` as @csarven suggested would also be fine but would need to be tied to a sufficiently clear definition matching our use. Being sufficiently clear for our use might make it too specific for `ldp`.

**Comment by csarven** [comment]
Sorry, I skipped a few steps. As per https://www.w3.org/2016/08/namespaces/#adding

>Terms MUST be clearly described, and if associated with a Working, Interest or Community Group specification, MUST link to that specification and note the status of the specification.

I think in context of the LDP-Next CG and adding new terms to the LDP namespace, the proposal needs to be accompanied with a spec. Even if that wasn't a requirement, I think it'd would probably strengthen the adoption of versioning - Memento being the best candidate - in LDP, for both read and write, meanwhile piggybacking on the LDP ns and having the spec under w3.org. Versioning in LDP as an extension for existing LDP implementations will probably have the least amount of friction.

So, if that sounds reasonable, the versioning parts in the Fedora spec - basically where LDP and Memento meet - would need to be extracted and put into its own spec.

`ldp:VersionedResource` was an example, but great that `memento:` is also on the table. Instead of a new `memento` ns, it may be worthwhile to consider putting those under `ldp` ns as well. `fcrepo:PreferInboundReferences` should probably move too. In any case, I'm less concerned about what these end up being called than the idea of isolating the requirements strictly about versioning.

On a related note: https://github.com/apache/marmotta has https://marmotta.apache.org/platform/versioning-module.html . However, I do not know if it has its own implementation of the *write* dimension of Memento in LDP. (By the looks of the code, it may only be read?). Investigating (aka LazyWebing) here: https://twitter.com/csarven/status/922157459363336192 . It'd be nice to coordinate.

**Comment by hvdsomp** [comment]
I would like to make a few observations, resulting from:

- working with @csarven on issues related to resource versioning, LDP
- discussions with Fedora colleagues regarding their use of Memento for access to versions in the the Fedora API

First, I obviously strongly endorse the use of the Memento protocol for read access to resource versions in the Fedora API. It would be nice if that approach eventually could find its way into an updated LDP spec. With this regard, based on discussions with the Fedora team, I still wonder whether the choice to make URI-R and URI-G coincide is the most appropriate.

The discussions with the Fedora team also led me to understand that there are really two kinds of versions in Fedora (and in general, really): 

- `living versions` that are subject to change 
- `locked versions` that will no longer change past a certain date

With this regard, the Memento protocol states: _The presence of a "Memento-Datetime" header and associated value for a given response constitutes a promise that the resource state reflected in the response will no longer change._

This means that, as per RFC7089, only a `locked version` qualifies as a Memento and hence carries a `Memento-Datetime`. The state of a `living version` is still subject to change and hence it should not carry a `Memento-Datetime`. Both the `living` and `locked` versions should carry a `link=original` to indicate their version relationship with the original resource; and they could be interlinked e.g. using `rel=prev` and `rel=next`.  But, whereas the locked version carries a `Memento-Datetime`, the living version should carry a `Last-Modified`.  Following the same logic, a living version isn't really subject to the Memento protocol and hence isn't really accessible via a TimeGate or TimeMap. Now, that is obviously as per the letter of RFC7089 and the spirit could be different. For example, I could see how both `locked versions` and `living versions` could be accessible via TimeGate and TimeMap because that just makes a lot of sense from an implementation perspective. But, in this case, I do still think that distinguishing between the use of Memento-Datetime (`locked`) and Last-Modified (`living`) would be appropriate. 

All of the above was about read access to resource versions. But I do think that the notions of `locked versions` and `living versions` also apply to writing versions. And I would be very interested in exploring how this could be optimally achieved from a LDP perspective, using the Fedora API as a concrete testing ground. 

As a result of work with @csarven, I have read and re-read the Fedora API and I have started to wonder about section 4.5.2 in which two ways are described to create versions: 

- HTTP PUT/PATCH against an LDPRv, and  
- HTTP POST against an LDPCv, 

and how this all relates to the notion of `locked` and `living` versions. 

Two questions, requests for comment with this regard:

1. Could one imagine creating versions by merely interacting with the LDPCv? After all, the LDPCv is discoverable via `rel=timemap` provided by the LDPRv. And if this could be done, how could one distinguish between the creation of a `locked` and `living` version using an approach that aligns with LDP practice? 
2. Or is the distinction between HTTP PUT/PATCH against an LDPRv and  HTTP POST against an LDPCv exactly related to the notion of `locked` and `living` versions, with the former being about `living` and the latter about `locked`?

**Comment by csarven** [comment]
re whether URI-R and URI-G must coincide or not, created issue https://github.com/fcrepo/fcrepo-specification/issues/252 as a proposal to detach URI-R from URI-G.

**Comment by whikloj** [comment]
@hvdsomp

If the presence of a Memento-Datetime header indicates that the resource is locked then it is possible (and I'm no LDP nor Memento wizard) that using the [200 date time negotiation](http://mementoweb.org/guide/rfc/#Pattern1.2) method would be a problem. 

However if you operate using the [302 Found date time negotiation](http://mementoweb.org/guide/rfc/#Pattern1.1) method then I think there is no conflict.

This is what we are looking at for now due to other constraints.

ie.
```
PUT /LDPRv - Create a versionable LDP-RS resource (this also creates the LDPCv)
POST /LDPRv/LDPCv - Creates a Memento of LDPRv at this instant and stores it.
GET /LDPRv - 200 response, get the current resource (the living version)
GET /LDPRv with Accept-Datetime - 302 response Location: /LDPRv/LDPCv/LDPRm (no Memento-Datetime header)
GET /LDPRv/LDPCv/LDPRm - 200 response with the Memento-Datetime header.
```

**Comment by barmintor** [comment]
I'm also 👍  on `memento:OriginalResource`.

**Comment by hvdsomp** [comment]
I worked on a Memento ontology. The first stab is at http://mementoweb.org/ns.rdf

Feedback very welcome. I left an open issue in a comment in the ontology doc.

We will eventually put RDF/XML, Turtle, and maybe JSON-LD up and support content negotiation with http://mementoweb.org/ns

**Comment by zimeon** [comment]
Since we now have `memento:OriginalResource` == `http://mementoweb.org/ns#OriginalResource` I'd say we go with that. Seems that there are already :+1:'s from all editors except @dannylamb

**Comment by hvdsomp** [comment]
* I changed memento-datetime to mementoDatetime as suggested on memento-dev

* I got some help to use OWL to express the following:

On the condition that there is an "original" link between a Memento and an OriginalResource, the following holds: 
`<mem:Memento ont:isSameWorkAs mem:OriginalResource>`. 
It's the weird stuff in the ontology with the #Y and owl:onProperty and owl:someValuesFrom.

* There are now 3 versions available:
- [http://mementoweb.org/ns.rdf](http://mementoweb.org/ns.rdf)
- [http://mementoweb.org/ns.rdf](http://mementoweb.org/ns.ttl)
- [http://mementoweb.org/ns.jsonld](http://mementoweb.org/ns.jsonld)

* Early next week we will set up content negotiation with http://mementoweb.org/ns and make sure all mime types etc are correct.
