### ISSUE TITLE
Clarify LDPRm General

### ISSUE THREAD

**Issue by csarven** [fcrepo/fcrepo-specification#249]
re https://fcrepo.github.io/fcrepo-specification/#LDPRm-general

* "it is created as both an LDPR and a Memento" -- Should "LDPR" be "LDPRv"?

* In "An LDPRm MUST be invariant: While it MAY be deleted, it MUST NOT be modified once created." the "MUST be invariant" is not particularly testable. It may be simpler to just say "An LDPRm *MAY* be deleted, but *MUST NOT* be modified once created."

**Comment by escowles** [comment]
I think the intention with "it is created as both an LDPR and a Memento" is that the resource is created as specified, and it is also created as a Memento resource representing that version.  So if you create a LDPR with the `fcrepo:VersionedResource` type, and then went to its TimeMap, there would be one LDPRm listed representing the initial state of the resource.

I agree with your wording change — "An LDPRm MAY be deleted, but MUST NOT be modified once created." seems clearer to me.

**Comment by zimeon** [comment]
If the intention is that 2 resources must be created for a versioned resource (one the LDPRv and an identical copy, an LPPRm) then I think we need to clarify the language further. The current _"*it* is created as both an LDPR(v) and a Memento"_ is confusing because of the singular _*it*_. Something along the lines of _"two resources are created with the same content: and LPPRv and a Memento (LDPRm)"_

Having said that, it is necessary to say that an implementation MUST create a separate LDPRm initially? Would it not be reasonable for an implementation to create just the LDPRv and the LDPCv initially, and only create an LDPRm when the LDPRv is updated (server managed) or when there is an explicit request to do so (client managed)?

**Comment by awoods** [comment]
That is a good point, @zimeon. Let's decide on the functionality first, then the wording.

When a resource is created or converted into an LDPRv, I would be inclined to have an LDPCv auto-created, but not an LDPRm... despite the current wording.

**Comment by zimeon** [comment]
@awoods I have the same inclination

**Comment by zimeon** [comment]
Reopened after auto-close from the #253 PR which did not address the latest aspect being discussed

**Comment by escowles** [comment]
I'm not sure — if the LDPRm isn't auto-created when a LDPRv is created, then would you be able to get the current version of the resource from the LDPCv if the current version was the only version?

**Comment by barmintor** [comment]
I think it's reasonable to suggest that, if the LDPRm is *not* automatically created, that "current" `should not` be presented as a datetime negotiable memento, since the same memento request could have different responses over time.

**Comment by escowles** [comment]
👍 OK, then it sounds like we're agreed that we shouldn't create an LDPRm.

**Comment by dannylamb** [comment]
I'm :+1: for not creating a memento automatially and allowing the resource to live as the original version until a memento is created by a user.

**Comment by barmintor** [comment]
Just to clarify that also means that if you are GET'ing the LDPCv that has no LDPRm, it's empty and you have to rely on the `Link rel=original` header to get current content.
