### ISSUE TITLE
Clarify reliable method to write into LDPCv

### ISSUE THREAD

**Issue by csarven** [fcrepo/fcrepo-specification#250]
https://fcrepo.github.io/fcrepo-specification/#httpPOST states:

>Any LDPC MUST support POST ([LDP] 4.2.3 / 5.2.3).

which I assume to include LDPCv here.

However, https://fcrepo.github.io/fcrepo-specification/#ldpcvpost is a bit confusing since the first two paragraphs start with (emphasis on the *if*):

>If an LDPCv supports POST..

as well as (emphasis on the *if*):

> Non-normative note: If an LDPCv does not Allow: POST 

Why would it not support `POST`?

This is especially important because for `PATCH` https://fcrepo.github.io/fcrepo-specification/#ldpcvpatch (emphasis on the *MAY*): 

> An implementation MAY Allow: PATCH

And `PUT` is implicitly a *MAY* because it is not mentioned.

Hence, there should be at least one method to write into a container. Correct?

If the intention with LDPCv is that it requires `POST`, then the first paragraphs at https://fcrepo.github.io/fcrepo-specification/#ldpcvpost need not start with the condition, and the non-normative note paraphrased.

**Comment by escowles** [comment]
The main use case for an LDPCv not supporting POST is when the server manages creation of versions automatically (rather than having the client explicitly create them).  So each modification by a client would automatically create a version in the corresponding LDPCv, so there wouldn't be any need for the client to explicitly POST to it to create a version.

But I agree that it is at odds with the earlier requirement for an LDPC to support POST.  I'm not sure how that would be resolved.  We could update the earlier section to require only non-LDPCv containers to support POST.

**Comment by dannylamb** [comment]
Yeah, we're definitely contradicting ourselves here.  I'm not sure how best in normative language to say we have a subset of containers that are excluded from a rule.  Can we say MUST but note the exception, or does that force us to soften the requirement to SHOULD?

**Comment by barmintor** [comment]
I don't think we're contradicting ourselves exactly: If an LDP-Cv supports POST, the client is expected to initiate storage of a locked version. PATCH (if supported) allows writing triples describing the LDPCv, but ought not to creating resources. But it is also possible that an implementation track all changes, with timestamps, and not allow such client initiation (in fact, an early impl does). In that case, the LDPCv would not advertise any write methods in HTTP OPTIONS. Does that clarify or obscure @csarven

**Comment by escowles** [comment]
@barmintor But we say that LDPC MUST support POST (https://fcrepo.github.io/fcrepo-specification/#httpPOST).

So I think we can say that LDPCv is an exception, that it does not need to support POST.

**Comment by barmintor** [comment]
Oh, I see (and apologies to @csarven ) - I don't know what our language options are here.

**Comment by zimeon** [comment]
I think there is a compelling use case (server managed versioning) for not allowing POST on LDPCv so this boils down to a language question IMO.

It might be we have to do something as ugly as "Any LDPC (except LDPCv, see X.Y) MUST support POST..."

**Comment by escowles** [comment]
@zimeon Or, we could relax that to "Any LDPC SHOULD support POST..." — potentially moving us closer to allowing a read-only implementation.

**Comment by zimeon** [comment]
I think the wording issue remains whether LDPC in general SHOULD or MUST support POST -- in the case of LDPCv it is neither SHOULD nor MUST. So I think we want something like the suggestion in https://github.com/fcrepo/fcrepo-specification/issues/250#issuecomment-339594844

To the question of whether want to relax MUST to SHOULD anyway, I agree that would make a read implementation "compliant" but I'm not sure what use that version of compliant is. I'd be as happy for someone with a read-only implementation to have to say "read-only but otherwise compliant".

**Comment by zimeon** [comment]
Agreement in editors' call today that we should resolve the inconsistency around support for POST, we will not add in the issue of whether to relax requirement for POST support in general.
