### ISSUE TITLE
Numbering scheme?

### ISSUE THREAD

**Issue by escowles** [fcrepo/fcrepo-specification#280]
Should the final recommendation be numbered? 1.0?

**Comment by zimeon** [comment]
I see two options:

  * The API spec is separate and new so we number it 1.0 where released
  * The API is tied to the next version of community Fedora so we number it 5.0

Although I see some community confusion with the former (_"so Fedora 5.0 implements the API 1.0?"_) I think this is probably still the way to go. I imagine the community Fedora will do 5.0 5.1 5.2 while still following the first API recommendation, because there is much not specified in the API that would still require semantic versioning of the implementation. It would seem even more confusing to have Fedora 5.1.3 that implements the Fedora API 5.0 than it would have have 5.1.3 implements the Fedora API 1.0.

**Comment by awoods** [comment]
:+1: to the initial Recommendation being released as 1.0.0

**Comment by dannylamb** [comment]
Agreed.  Other implementations will follow it too, so I don't see much sense in tying it to the community impl version.

**Comment by escowles** [comment]
👍  to 1.0.0

**Comment by dannylamb** [comment]
@barmintor?

**Comment by bseeger** [comment]
What would each letter in x.y.z mean in this case?  Most specs seem to have a x.y scheme - so I'm curious as to what the z would represent.  Thanks!

**Comment by escowles** [comment]
@bseeger I would expect to use the z level for trivial changes (typos, etc.)

**Comment by zimeon** [comment]
@bseeger e.g. IIIF use of [semantic versioning](http://iiif.io/api/annex/notes/semver/)

**Comment by barmintor** [comment]
I trust Esmé and IIIF, :+1: for 1.0.0

**Comment by bseeger** [comment]
@zimeon, thanks for the info.  I didn't realize that semantic versioning had entered the specification realm.  To understand this better -- when someone's piece of software is compliant with a version of the spec -- will it just say it's compliant with the major.minor?  How does this ripple into testing compliance in the Fedora API Test Suite?  It's probably a separate question for maybe a different group, but it does make me wonder what level of compliance the test suite will test for -- will it be able to identify if something is, say, 1.0.0 compliant or, separately, 1.2.3 compliant?  I realize that the PATCH changes will mostly be fixing typos, but I wonder what effect this would have on the test suite, if any.  Mostly thinking out loud.

**Comment by escowles** [comment]
I'd expect the API Test Suite to be versioned with Major.Minor versions that match the spec and verify compliance with that (the Patch level shouldn't have any testable changes).

**Comment by awoods** [comment]
@escowles : agreed. I would also expect the TCK to be testing at the specification major.minor granularity.

**Comment by zimeon** [comment]
Propose `close - done` -- we agreed 1.0.0, this is implemented in #334, and is on the #330 release checklist

**Comment by escowles** [comment]
👍 to closing this issue, and merging #334 when we release 1.0

**Comment by awoods** [comment]
Will be resolved with: https://github.com/fcrepo/fcrepo-specification/pull/334
