### ISSUE TITLE
Section 3.1.1 Must vs SHOULD

### ISSUE THREAD

**Issue by whikloj** [fcrepo/fcrepo-specification#332]
In testing the Modeshape impl, I was reading the spec and I found this interesting paragraph

> LDP Containers MUST distinguish [containment triples] from [membership] and [minimal-container] triples. If an implementation cannot make this distinction,...

It seems to me that if you **MUST** do something then there is no reason to define what to do if you cannot do that. Defining how you are expected to act if you can't perform this action, makes this seem like a **SHOULD**

**Comment by escowles** [comment]
I think this is a wording issue where we use "distinguish" in different senses.

The requirement is that containers must distinguish between containment and user-managed triples.  There are two ways that this may be handled:

1. If the server can allow user-managed triples with `ldp:contains`, and keep those separate from server-managed containment triples, then that's OK.
2. If the server can't keep those triples separate, then it must not allow user-managed triples with `ldp:contains`.

Instead of "If an implementation cannot make this distinction", maybe we should say "If user-managed triples using `ldp:contains` would prevent an implementation from making this distinction,"?

**Comment by whikloj** [comment]
"A server that allows user-managed triples with the `ldp:contains` predicate **MUST** be able to keep those user-managed triples separate from server-managed containment triples. If a server cannot keep these two uses of `ldp:contains` separate then any request to use `ldp:contains` as the [membership predicate] for LDP Direct and Indirect Containers or as a client-managed property **MUST** be rejected with a `409 (Conflict)`."

**Comment by escowles** [comment]
@whikloj 👍 that looks good to me

**Comment by whikloj** [comment]
@escowles awesome, sorry to get bogged down in wording but it keep confusing me.

**Comment by escowles** [comment]
No worries @whikloj ! The new text is much better, and this will help other people from being confused.  Can you make a PR, or do you want me to?

**Comment by zimeon** [comment]
@whikloj :+1: -- your suggestion is much easier to understand. I'll make a PR (since it seems easiest for one of us editors to deal with the formatting and validation requirements)

**Comment by zimeon** [comment]
I think we need s/user-managed/client-managed/ in the suggested text to align with language in the rest of the spec

**Comment by whikloj** [comment]
Thanks for taking this on @zimeon and @escowles. 👏
