### ISSUE TITLE
LDP-NR headers on GET and HEAD for `redirect` handling

### ISSUE THREAD

**Issue by awoods** [fcrepo/fcrepo-specification#345]
In the case of `redirect` handling of external content, what is an example expectation for `LDP-NR` headers?

Is it reasonable to expect:
```
** Link: type=ldp:NonRDFSource
** Link: type=ldp:Resource
** Link: type=describedby
** Digest: 123
** Content-Type: abc
```
...with a 301 status code?

**Comment by bbpennel** [comment]
Those headers look reasonable, probably with a `Location` header added in.  

I am wondering if the status code should be either 302 or 307.  Both of those would imply that future requests should start by coming back to the Fedora URL, in case the external binary location gets updated in the future. 307 would just add the implication that the request should be repeated with the same method, which would be the behavior we'd expect, but might be a bit of an assumption on Fedora's part since it doesn't know much about what its redirecting to.

**Comment by zimeon** [comment]
I agree with @bbpennel - 307 or 302 with `Location` - both status codes seem fine, I think a server could use either depending on circumstances.

Is the proposal here to refine the statements in [3.9 External Binary Content](https://fcrepo.github.io/fcrepo-specification/#external-content):

> A Fedora server receiving requests that would create or update an LDP-NR with content external to the request entity MUST reject request if it cannot guarantee all of the response headers required by the LDP-NR interaction model in this specification.

with a more specific (and thus easier to understand/clearer to test) list of headers that must be supported? That seems sensible to me.
