### ISSUE TITLE
Use cases for #129

### ISSUE THREAD

**Issue by scossu** [fcrepo/fcrepo-specification#408]
This is more of a question than a feature request. As I read issue #129, that drives [3.1.1](https://fedora.info/2018/11/22/spec/#ldpc), I am having a hard time finding practical use cases that justify allowing the use of LDP predicates such as `ldp:contains`. 

@barmintor makes an example: 

> a DirectContainer that uses ldp:contains as its memberRelation.

But I am still uncertain about the necessity or usefulness of using specifically `ldp:contains`. That seems to blur the lines between the concepts of containment and membership, and introduces complication for implementations that have to keep those terms separate. 

I think it would be reasonable and practical to keep a clear separation between terms that are under control of the software from terms that have no side effect on it, and are completely managed by the client. That separation can be naturally made by the `ldp` namespace. 

Where client interaction with `ldp:` terms is necessary, as in [3.6](https://fedora.info/2018/11/22/spec/#http-put) to define or change interaction model, the range of action of the client should be tightly controlled and the client should be aware of server-side implications of actions on those terms. 

I would be in favor of at least discouraging (`SHOULD NOT`) arbitrary manipulation of LDP terms. However, I may not be thinking about particular use cases that may require more freedom in handling those terms. 

Thoughts are appreciated.

**Comment by barmintor** [comment]
That section was written as a negotiation between prospective implementations who specifically did not want to carve out data exemptions and those that might. If an implementation falls into the latter camp, it is only required to reject the request - which I presume it would anyway.

I would also caution against the presumption that the spec editors were posting issues in the "first person", or whether the comments in the issues currently represent all of the conversation at the time.

**Comment by scossu** [comment]
I wrote my comment only based on the conversation on #129, but if there is more to it I'd be interested in reading more. 

The point of my comment is that the spec should prevent unnecessary confusion or complexity in its implementation as much as possible. I believe that a stricter control on LDP terms would be beneficial in this sense.  But if some strong use cases for more relaxed rules on containment have been brought up, I would understand better why the spec says so. At the moment, as I read 

> [implementations] may allow the creation of other triples with the ldp:contains predicate, and thus triples with this predicate do not necessarily imply containment. 

I find it quite confusing. Which containment are we discussing here? shall we not just clearly state that `ldp:contains` represents a reserved mechanism of the LDP server, and that other vocabularies should be used for user-defined concepts of containment?

**Comment by scossu** [comment]
p.s. to be clear, I understand that I can easily disallow the feature in a specific implementation. I am raising this for the spec's overall clarity's sake.

**Comment by escowles** [comment]
@scossu I appreciate the desire for clarity here, but I think the fact that the spec (and LDP) are unopinionated on the underlying model is the source of this variability: [3.1.6](https://fedora.info/2018/11/22/spec/#data-model).  As @barmintor mentioned, this outcome is the result of balancing the perspectives of different implementations that had different considerations on this point, and so the spec is deliberately neutral on the question.  I will point out that one benefit is that a Fedora implementation could support arbitrary RDF (including `ldp:contains` triples), which is something people have expressed interest in at various points.  It would certainly broaden the kinds of RDF management that Fedora could be used for.

So I think the prefer headers spelled out in [3.1.1](https://fedora.info/2018/11/22/spec/#ldpc) are the best way to tell the difference between server-managed containment, as opposed to `ldp:contains` triples that might be supplied by a client, or otherwise present but not indicate containment in the sense of managing the lifecycle of the resources that are the objects of `ldp:contains` triples.

**Comment by scossu** [comment]
Still not convinced of the usefulness of this, but if it is a negotiation that has been abundantly discussed, I'll gladly close the issue.
