### ISSUE TITLE
Does Persistence Fixity belong in the specification?

### ISSUE THREAD

**Issue by acoburn** [fcrepo/fcrepo-specification#90]

**Comment by acoburn** [comment]
Before including a notion of persistence-fixity in the specification, I think it will be necessary to answer a few questions and provide a solid justification.

First, in what fundamental ways does persistence-fixity differ from transport-fixity? And what is it about persistence-fixity that cannot be handled by the existing transport-fixity mechanism (e.g. `Want-Digest`)?

Second, Fedora is concerned about resource durability, but what does that mean? What if an implementation was entirely in-memory? Would that mean that the implementation was, by definition, not a Fedora? What if that in-memory Fedora is distributed across lots and lots of servers, such that it has an up-time that far exceeds an implementation that uses a file-based persistence strategy?

Third, what if Fedora is built on top of Spark? And the resources exist as "resilient distributed datasets" in which "persistence" is thought of as something really quite different?

Finally, given that Fedora operates with clients entirely through HTTP, it follows that Resources consist of HTTP Bodies or _representations_. What, then, does "persistence fixity" mean? And how does transport-fixity not address the various needs to ensure data integrity for resources?

**Comment by ajs6f** [comment]
I want to speak only to one of @acoburn's questions:

> Second, Fedora is concerned about resource durability, but what does that mean? 

There is a long tradition of defining it very precisely: a resource is durable when its _meaning_ is preserved through time (via semantic transparency and thoughtful, fine-grained content modeling). This is as opposed to having its _form_ preserved through time, which is what is supported by the use of fixity measurements. So the 'D' in Fedora has no relevance here, and whatever color of bucket into which bits are put (RAM, local disk, Spark RDDs elsewhere on the local network, "cloud storage", the akashic records…) doesn't matter for the question of durability.

**Comment by escowles** [comment]
> And what is it about persistence-fixity that cannot be handled by the existing transport-fixity mechanism (e.g. Want-Digest)?

Section 3.5.2: https://fcrepo.github.io/fcrepo-specification/#httpGETLDPNR says:
> GET requests to any LDP-NR must correctly respond to the Want-Digest header defined in [RFC3230] unless the Content-Type of the LDP-NR is a message/external-body extension.

I would like to verify the fixity of a LDP-NR without retrieving it.  I do not see any mention of using a Want-Digest header in a HEAD request, but if that is allowed, it would satisfy this use case.  If that is not allowed, I remember there were several mechanisms proposed for handling this, and I think it would be good to revisit the other alternatives.

Re: Durability — I agree with Adam's [comment](https://github.com/fcrepo/fcrepo-specification/issues/90#issuecomment-292804256) that resource durability does not necessarily mean bit-level immutability.  Over time, I would expect format migrations to change many LDP-NRs.  But absent intentional change, bit-level fixity checking is an important tool to guard against storage failures, unintentional modification, etc.

**Comment by ajs6f** [comment]
I don't pretend to much deep knowledge here, but I see nothing in the [RFC](https://tools.ietf.org/html/rfc3230#section-4.3.1) that would either encourage _or_ prevent the use of `Want-Digest` with `HEAD`.

**Comment by barmintor** [comment]
I like to think that [RFC 7231](https://tools.ietf.org/html/rfc7231#section-4.3.2) means that we don't have to call HEAD out for every header interaction we specify for GET, but I may be too lax here- and I could also see the argument that the Digest response header is a payload header, tho the version of the HTTP spec 3230 was presumably written to doesn't carve out [that exception](https://tools.ietf.org/html/rfc2616#section-9.4)?

**Comment by barmintor** [comment]
That is to say, I found what I understand was the conclusion y'all arrived at last [December](https://wiki.duraspace.org/display/FF/2016-12-08+-+Fedora+Tech+Meeting) to be pretty convincing re: the ability to call it a day after `Want-Digest`, which I assumed included HEAD requests, but I wasn't on that call.

**Comment by birkland** [comment]
Persistence fixity answers the question:  Has data stored/persisted somewhere changed (storage failure, unintentional modification, etc)?

Transport fixity answers the question:  Is the data received the same as the data that was sent?
 
`Want-Digest` is sufficient for determining persistence fixity if and only if the digest returned is equivalent to the digest of the persisted data.  If that were codified in the spec, then `Want-Digest` alone is suitable for fixity-checking use cases.

... however, as @acoburn notes, maybe the notion of persistence or fixity simply may not apply to certain kinds of resources.  If that's the case, then the semantics of `Want-Digest` can really only be transport-related.  In this world, if a client needs to verify fixity of a given resource, then it would need to reason about the nature of the resources in order to figure out whether persistence fixity is an applicable concept, and figure out how to do it (or otherwise know that it doesn't have to, e.g. if a storage layer provides absolute, irrevocable guarantee of integrity that can be presumed fact).

Back in the Fedora 3 days, some details related to persistence were ... persisted (in FOXML), and could be read, modified, etc by clients.   In contemporary Fedora that's not necessarily the case, unless you put such details in the repository yourself (or they're server managed by a Fedora implementation).  Doing so might suit fixity checking use cases quite well.

I think an API that allows persistence fixity checking may be useful, but there would need to be some sort of discoverability aspect available to clients.  At that point, however, I'm wondering if the need for persistence fixity is too specialized to include in the broader spec.

**Comment by awoods** [comment]
Assuming `Want-Digest` also applies to `HEAD` requests, is there consensus that the client-side approach for fixity verification is sufficient?
If so, I would suggest closing this issue with the explicit clarification that `HEAD` should be supported, along the lines of:
* https://fcrepo.github.io/fcrepo-specification/#http-head
* https://fcrepo.github.io/fcrepo-specification/#http-head-1

**Comment by birkland** [comment]
@awoods.  The phrasing of "Assuming Want-Digest also applies to HEAD requests, is there consensus that the client-side approach for fixity verification is sufficient?" is a little imprecise.  Can you confirm that this means:
* `Want-Digest` applies to `HEAD` requests, and is a mechanism of conveying _transmission_ fixity.
* While there is no specific mechanism for conveying _persistence_ fixity in the specification, clients have various means at their disposal to do so (e.g. through data modeling, engaging storage devices, deploying services, etc), otherwise known as a "client-side approach"

**Comment by escowles** [comment]
@birkland I think doing a HEAD with a `Want-Digest` header is a client-side approach to persistence fixity.  That is, it's a way for the client to retrieve the current checksum with the preferred algorithm, which can be compared against the stored checksum (either locally managed by the client, or stored in a property on the binary, etc.).  So the server does not need to explicitly perform a fixity check, but it provides the client with enough information to verify bit-level fixity.

**Comment by ajs6f** [comment]
`Want-Digest` uses a single small registry of simple checksums. It completely fails to accomplish the major use case for fixity I offered, under any circumstance.

**Comment by awoods** [comment]
@escowles : Thanks for your clarifying text. That is what I had in mind. 
@birkland : As @escowles commented, my opinion is that `Want-Digest` conveys _persistence_ fixity as opposed to _transmission_ fixity... although whether the server recalculates the returned digest or retrieves a stored value is implementation-dependent.
@ajs6f : Are you advocating for removal of `Want-Digest` from the spec? Or are you suggesting something else?

**Comment by ajs6f** [comment]
I am just remarking that shrinking the functionality of the service reduces the use case coverage. At some point, it's no longer worth supporting.

**Comment by barmintor** [comment]
@awoods it's hard to read the RFC for Want-Digest in a way that suggests using a previously stored value would be appropriate, maybe we should note that expectation in a non-normative section?

**Comment by escowles** [comment]
That's a good point, @ajs6f — some notion of fixity beyond bit-level fixity would allow an implementation to address the use case you outlined.  The `Want-Digest` header we're talking about here, and the `Expect-Digest` digest header discussed in #87/#88 all revolve around checksums.  Is there an alternative mechanism that would be more flexible?

**Comment by birkland** [comment]
@awoods @escowles I think the point that @acoburn made is that the nature of a resource can be nuanced, the notion of persistence and maybe even fixity may not be straightforward, or not applicable.  So `Want-Digest` is only equivalent to persistence fixity if you know that the resource is persisted, has a notion of fixity outside of a particular http interaction with a client, and that its fixity can be conveyed as a value (the digest).

**Comment by escowles** [comment]
@birkland Yes, I agree that those are the constraints.  They align with my expected circumstances, and so `Want-Digest` on a HEAD request would satisfy my use case.  Beyond that, I would say that any implementation could generate the response body and checksum it — that may not be efficient, but it's almost certainly better than the alternative (having the client actually retrieve the binary and determine fixity for itself).

But as I said earlier, I'm definitely interested in other notions of fixity and how they might be accommodated in the spec.  Do you have any thoughts about that?  I don't have any experience with persistence layers that don't conform to those constraints, so I really can't say whether this is some other notion, or whether they would have to defer to the client.

**Comment by zimeon** [comment]
IMO `Want-Digest` with `HEAD` meets the use case of client-side persistence fixity checking while avoiding a download (ie. computation potentially close to storage). I agree that it takes much nuance out of fixity (good or bad depending on use case) by restricting to digest over representation bytestream of corresponding `GET`. A plus is clarity.

It seems to me that any more complex notion of fixity would not have consensus support and thus would not be "core", but could perhaps be considered as an add-on spec.

**Comment by birkland** [comment]
In addition to @barmintor's suggestion that non-normative text should emphasize that `Want-Digest` is a computed value, non-normative text should also explain that `Want-Digest` with `HEAD` may be used as the basis for persistence fixity checking if it is known that a given resource is persisted in storage, has a notion of fixity outside a particular http interaction with a client, and that its fixity can be conveyed as a value (the digest) - or something along those lines.

**Comment by escowles** [comment]
The spec as it stands now requires that implementations support creation of LDP-NRs, with a `Digest` header, and that they respond to a GET with a `Want-Digest` header with a response that includes the appropriate `Digest` header.  So it follows that the implementation must be able to calculate a checksum of an LDP-NR it has created and compare it to the provided checksum, and that it can also retrieve the content later and checksum it.  IMHO, we should codify this by explicitly requiring that that HEAD also support `Want-Digest` and produce `Digest` headers in the response.

I agree with @zimeon that any more complex notion of persistence-fixity is unlikely to gain consensus, and should be taken up as a separate spec.  But I don't think that should prevent us from including the bit-level persistence-fixity in the spec.
